
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: goAPI-database
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/goAPI-database:/var/lib/postgresql/data
    env_file:
      .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5